CREATE DATABASE ECOMM;
USE ECOMM;
 CREATE TABLE USERS(
	USERNAME VARCHAR(20) PRIMARY KEY,
    FULLNAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(35) NOT NULL,
    MOBILE VARCHAR(13),
    PASSWORD VARCHAR(30)
);
SELECT * FROM USERS;

CREATE TABLE CART(
	CART_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRODUCT_PRICE INT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
SELECT * FROM CART;

CREATE TABLE ORDERS(
	ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    USERNAME VARCHAR(255),
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_PRICE FLOAT,
    QUANTITY INT 
);
SELECT * FROM ORDERS;
INSERT INTO ORDERS (USERNAME,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,QUANTITY)
SELECT USERNAME,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,QUANTITY FROM CART;